### ISSUE TITLE
Discussion about tags

### ISSUE THREAD

**Issue by lb-** [aledotgomez/magellan#2]
What are you thinking of using, this package looks great https://atmospherejs.com/patrickleet/tags

However it is not set up to use the audit-argument-checks and I am not sure if there is a way to bypass some packages or if a fork/issue request of that package would be needed.

beyond that, the tags package looks like it could work well if used with this ui tag package: http://timschlechter.github.io/bootstrap-tagsinput/examples/ or something similar.

**Comment by aledotgomez** [comment]
Thanks for the tip! I'll explore this package and see how to implement it on the project.
