### ISSUE TITLE
Kadira settings committed to repo

### ISSUE THREAD

**Issue by jshimko** [aledotgomez/magellan#3]
You may want to remove this...
https://github.com/aledotgomez/meteor-blog/blob/master/server/kadira.js

You'll be getting stats from everyone that clones your repo.  The better option would be to use `Meteor.settings` ([docs](http://docs.meteor.com/#/full/meteor_settings))

For example, 

```javascript
Kadira.connect(Meteor.settings.kadira.apiKey, Meteor.settings.kadira.apiSecret)
```

and then throw your api keys in your settings.json...

```json
{
  "kadira": {
    "apiKey": "YOUR KEY",
    "apiSecret": "YOUR SECRET"
  }
}
```
and start meteor with `meteor --settings path/to/settings.json`

**Comment by aledotgomez** [comment]
Thanks for the tip! I will implement this shortly. Will I have to start meteor every time with meteor --settings path/to/settings.json ?

**Comment by jshimko** [comment]
Yes.  However, you can make it really easy with bash aliases.  Just open your `.bash_profile` (should be at `~/.bash_profile`) and add something like:

```bash
alias m='meteor'
alias ms='meteor --settings path/to/settings.json'
```
Then make sure to reload your environment by closing and reopening your terminal or by running:  

```bash
source ~/.bash_profile
```

Now you can run `m` instead of `meteor` and `ms` instead of `meteor --settings settings.json`  (You can obviously call the aliases whatever you want.  The point is just to type less and not forget what your shortcuts are.)

For a little inspiration on what can be done with bash aliases and functions, check [this post][1] out.

[1]: http://natelandau.com/my-mac-osx-bash_profile/

**Comment by aledotgomez** [comment]
Thank you very much for your help! The changes have now been applied to the project.
